### PR TITLE
Added Support Of Django Unittests

### PR DESCRIPTION
**Pull request by mh-firouzjah**
# Added Support Of Django Unittests

- compatible with python 2 & 3
- defined as a new function
- does noting in case of exception to locate or import django and DAJNGO_SETTING_MODULE

the result is something like this:
Screenshot_20230717_085829

### CODE REVIEW

**Comment by mh-firouzjah** [comment]
@kondratyev-nv the last commit is compatible with both python 2 & 3 versions since there isn't any new version related syntax or staff used. it's just pure old python.

**Comment by kondratyev-nv** [comment]
Thanks for the PR! 
1. Can you please add a sample django app with tests in `test/test_samples`? The goal is to be able to see some sample tests discovered and run during debugging and for tests.
2. Can you please attach a screenshot or something of how this works?

**Comment by mh-firouzjah** [comment]
> Thanks for the PR!
> 
> 1. Can you please add a sample django app with tests in `test/test_samples`? The goal is to be able to see some sample tests discovered and run during debugging and for tests.
> 2. Can you please attach a screenshot or something of how this works?

Done!

**Comment by kondratyev-nv** [comment]
Can you please add a sample app with tests in test/test_samples? Something similar to the project you have on the screenshot. It'd be easy to verify and maintain that way. Thanks!

**Pull request closed without merging**
